version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-cli:
    image: redis:latest
    container_name: redis-cli
    depends_on:
      - redis
    entrypoint: ["redis-cli", "-h", "redis"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
