services:
  cleanup: #redis 초기화용
    image: redis:latest
    container_name: redis-cli
    entrypoint: [ "redis-cli", "-h", "redis", "FLUSHALL" ]
    networks:
      - redis-network
  k6:
    container_name: k6
    image: grafana/k6:latest
    depends_on:
      - cleanup
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./script:/scripts
    command: run /scripts/script.js
    networks:
      - monitoring-network



networks:
  monitoring-network:
    external: true

  redis-network:
    external: true